import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  intentText: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.55,
    margin: 0,
    fontStyle: "italic",
  } satisfies CSSProperties,
  badges: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  disclaimer: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--warn)",
  } satisfies CSSProperties,
  columns: { display: "flex", gap: 24, flexWrap: "wrap" } satisfies CSSProperties,
  column: { flex: "1 1 240px", minWidth: 0 } satisfies CSSProperties,
  listLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  list: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  scopeLabelIn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--ok)",
    marginBottom: 8,
  } satisfies CSSProperties,
  scopeLabelOut: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  scopeListIn: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    fontSize: 13,
    color: "var(--text-primary)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  scopeListOut: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    fontSize: 13,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  scopeItem: { lineHeight: 1.4 } satisfies CSSProperties,
  divider: {
    border: 0,
    borderTop: "1px solid var(--border)",
    margin: "4px 0",
  } satisfies CSSProperties,
  none: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sourceRef: { color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis" } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
