import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  chips: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  chip: {
    display: "inline-flex",
    gap: 6,
    alignItems: "baseline",
    padding: "4px 10px",
    border: "1px solid var(--border)",
    borderRadius: 999,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  chipValue: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  degraded: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 13,
    color: "var(--warn)",
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  warning: { fontSize: 13, color: "var(--warn)" } satisfies CSSProperties,
  tree: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,

  // SymbolGroup (child component)
  group: {
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  header: {
    all: "unset",
    boxSizing: "border-box",
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbol: { fontWeight: 600 } satisfies CSSProperties,
  file: { color: "var(--text-muted)", fontSize: 12 } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  body: {
    padding: "4px 12px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  callers: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 13,
  } satisfies CSSProperties,
  caller: { display: "flex", gap: 8, alignItems: "baseline", flexWrap: "wrap" } satisfies CSSProperties,
  callerName: { color: "var(--text-primary)" } satisfies CSSProperties,
  callerLoc: { color: "var(--text-muted)", fontSize: 12 } satisfies CSSProperties,
  link: { color: "var(--accent)", textDecoration: "none" } satisfies CSSProperties,
  facts: { display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" } satisfies CSSProperties,
  factsLabel: { fontSize: 12, fontWeight: 700, color: "var(--text-muted)" } satisfies CSSProperties,
  endpointChip: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 4,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  cronChip: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 999,
    border: "1px dashed var(--warn)",
    color: "var(--warn)",
  } satisfies CSSProperties,
} as const;
